//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrooperSetupOrganizer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstWeaponName {
            get {
                return ((string)(this["FirstWeaponName"]));
            }
            set {
                this["FirstWeaponName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstWeaponDPS {
            get {
                return ((string)(this["FirstWeaponDPS"]));
            }
            set {
                this["FirstWeaponDPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstWeaponElement {
            get {
                return ((string)(this["FirstWeaponElement"]));
            }
            set {
                this["FirstWeaponElement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstWeaponExotics {
            get {
                return ((string)(this["FirstWeaponExotics"]));
            }
            set {
                this["FirstWeaponExotics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecondSetupName {
            get {
                return ((string)(this["SecondSetupName"]));
            }
            set {
                this["SecondSetupName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdSetupName {
            get {
                return ((string)(this["ThirdSetupName"]));
            }
            set {
                this["ThirdSetupName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FourthSetupName {
            get {
                return ((string)(this["FourthSetupName"]));
            }
            set {
                this["FourthSetupName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FifthSetupName {
            get {
                return ((string)(this["FifthSetupName"]));
            }
            set {
                this["FifthSetupName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentSetupNumber {
            get {
                return ((string)(this["CurrentSetupNumber"]));
            }
            set {
                this["CurrentSetupNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstSetupProfession {
            get {
                return ((string)(this["FirstSetupProfession"]));
            }
            set {
                this["FirstSetupProfession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecondSetupProfession {
            get {
                return ((string)(this["SecondSetupProfession"]));
            }
            set {
                this["SecondSetupProfession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdSetupProfession {
            get {
                return ((string)(this["ThirdSetupProfession"]));
            }
            set {
                this["ThirdSetupProfession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FourthSetupProfession {
            get {
                return ((string)(this["FourthSetupProfession"]));
            }
            set {
                this["FourthSetupProfession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FifthSetupProfession {
            get {
                return ((string)(this["FifthSetupProfession"]));
            }
            set {
                this["FifthSetupProfession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstSetupExpertise {
            get {
                return ((string)(this["FirstSetupExpertise"]));
            }
            set {
                this["FirstSetupExpertise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecondSetupExpertise {
            get {
                return ((string)(this["SecondSetupExpertise"]));
            }
            set {
                this["SecondSetupExpertise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdSetupExpertise {
            get {
                return ((string)(this["ThirdSetupExpertise"]));
            }
            set {
                this["ThirdSetupExpertise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FourthSetupExpertise {
            get {
                return ((string)(this["FourthSetupExpertise"]));
            }
            set {
                this["FourthSetupExpertise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FifthSetupExpertise {
            get {
                return ((string)(this["FifthSetupExpertise"]));
            }
            set {
                this["FifthSetupExpertise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GetCurrentSetupNumber {
            get {
                return ((string)(this["GetCurrentSetupNumber"]));
            }
            set {
                this["GetCurrentSetupNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecondWeaponName {
            get {
                return ((string)(this["SecondWeaponName"]));
            }
            set {
                this["SecondWeaponName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecondWeaponDPS {
            get {
                return ((string)(this["SecondWeaponDPS"]));
            }
            set {
                this["SecondWeaponDPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecondWeaponElement {
            get {
                return ((string)(this["SecondWeaponElement"]));
            }
            set {
                this["SecondWeaponElement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecondWeaponExotics {
            get {
                return ((string)(this["SecondWeaponExotics"]));
            }
            set {
                this["SecondWeaponExotics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdWeaponName {
            get {
                return ((string)(this["ThirdWeaponName"]));
            }
            set {
                this["ThirdWeaponName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdWeaponDPS {
            get {
                return ((string)(this["ThirdWeaponDPS"]));
            }
            set {
                this["ThirdWeaponDPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdWeaponElement {
            get {
                return ((string)(this["ThirdWeaponElement"]));
            }
            set {
                this["ThirdWeaponElement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdWeaponExotics {
            get {
                return ((string)(this["ThirdWeaponExotics"]));
            }
            set {
                this["ThirdWeaponExotics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FourthWeaponName {
            get {
                return ((string)(this["FourthWeaponName"]));
            }
            set {
                this["FourthWeaponName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FourthWeaponDPS {
            get {
                return ((string)(this["FourthWeaponDPS"]));
            }
            set {
                this["FourthWeaponDPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FourthWeaponElement {
            get {
                return ((string)(this["FourthWeaponElement"]));
            }
            set {
                this["FourthWeaponElement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FourthWeaponExotics {
            get {
                return ((string)(this["FourthWeaponExotics"]));
            }
            set {
                this["FourthWeaponExotics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FifthWeaponName {
            get {
                return ((string)(this["FifthWeaponName"]));
            }
            set {
                this["FifthWeaponName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FifthWeaponDPS {
            get {
                return ((string)(this["FifthWeaponDPS"]));
            }
            set {
                this["FifthWeaponDPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FifthWeaponElement {
            get {
                return ((string)(this["FifthWeaponElement"]));
            }
            set {
                this["FifthWeaponElement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FifthWeaponExotics {
            get {
                return ((string)(this["FifthWeaponExotics"]));
            }
            set {
                this["FifthWeaponExotics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstArmorName {
            get {
                return ((string)(this["FirstArmorName"]));
            }
            set {
                this["FirstArmorName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstArmorType {
            get {
                return ((string)(this["FirstArmorType"]));
            }
            set {
                this["FirstArmorType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstArmorProtection {
            get {
                return ((string)(this["FirstArmorProtection"]));
            }
            set {
                this["FirstArmorProtection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstArmorExotics {
            get {
                return ((string)(this["FirstArmorExotics"]));
            }
            set {
                this["FirstArmorExotics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecondArmorName {
            get {
                return ((string)(this["SecondArmorName"]));
            }
            set {
                this["SecondArmorName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecondArmorType {
            get {
                return ((string)(this["SecondArmorType"]));
            }
            set {
                this["SecondArmorType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecondArmorProtection {
            get {
                return ((string)(this["SecondArmorProtection"]));
            }
            set {
                this["SecondArmorProtection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecondArmorExotics {
            get {
                return ((string)(this["SecondArmorExotics"]));
            }
            set {
                this["SecondArmorExotics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdArmorName {
            get {
                return ((string)(this["ThirdArmorName"]));
            }
            set {
                this["ThirdArmorName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdArmorType {
            get {
                return ((string)(this["ThirdArmorType"]));
            }
            set {
                this["ThirdArmorType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdArmorProtection {
            get {
                return ((string)(this["ThirdArmorProtection"]));
            }
            set {
                this["ThirdArmorProtection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdArmorExotics {
            get {
                return ((string)(this["ThirdArmorExotics"]));
            }
            set {
                this["ThirdArmorExotics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FourthArmorName {
            get {
                return ((string)(this["FourthArmorName"]));
            }
            set {
                this["FourthArmorName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FourthArmorType {
            get {
                return ((string)(this["FourthArmorType"]));
            }
            set {
                this["FourthArmorType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FourthArmorProtection {
            get {
                return ((string)(this["FourthArmorProtection"]));
            }
            set {
                this["FourthArmorProtection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FourthArmorExotics {
            get {
                return ((string)(this["FourthArmorExotics"]));
            }
            set {
                this["FourthArmorExotics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FifthArmorName {
            get {
                return ((string)(this["FifthArmorName"]));
            }
            set {
                this["FifthArmorName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FifthArmorType {
            get {
                return ((string)(this["FifthArmorType"]));
            }
            set {
                this["FifthArmorType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FifthArmorProtection {
            get {
                return ((string)(this["FifthArmorProtection"]));
            }
            set {
                this["FifthArmorProtection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FifthArmorExotics {
            get {
                return ((string)(this["FifthArmorExotics"]));
            }
            set {
                this["FifthArmorExotics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstWeaponElementDamage {
            get {
                return ((string)(this["FirstWeaponElementDamage"]));
            }
            set {
                this["FirstWeaponElementDamage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecondWeaponElementDamage {
            get {
                return ((string)(this["SecondWeaponElementDamage"]));
            }
            set {
                this["SecondWeaponElementDamage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdWeaponElementDamage {
            get {
                return ((string)(this["ThirdWeaponElementDamage"]));
            }
            set {
                this["ThirdWeaponElementDamage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FourthWeaponElementDamage {
            get {
                return ((string)(this["FourthWeaponElementDamage"]));
            }
            set {
                this["FourthWeaponElementDamage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FifthWeaponElementDamage {
            get {
                return ((string)(this["FifthWeaponElementDamage"]));
            }
            set {
                this["FifthWeaponElementDamage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EditButtonEnabled {
            get {
                return ((bool)(this["EditButtonEnabled"]));
            }
            set {
                this["EditButtonEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstRobeName {
            get {
                return ((string)(this["FirstRobeName"]));
            }
            set {
                this["FirstRobeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecondRobeName {
            get {
                return ((string)(this["SecondRobeName"]));
            }
            set {
                this["SecondRobeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdRobeName {
            get {
                return ((string)(this["ThirdRobeName"]));
            }
            set {
                this["ThirdRobeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FourthRobeName {
            get {
                return ((string)(this["FourthRobeName"]));
            }
            set {
                this["FourthRobeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FifthRobeName {
            get {
                return ((string)(this["FifthRobeName"]));
            }
            set {
                this["FifthRobeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstSetupName {
            get {
                return ((string)(this["FirstSetupName"]));
            }
            set {
                this["FirstSetupName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstSaberCrystal {
            get {
                return ((string)(this["FirstSaberCrystal"]));
            }
            set {
                this["FirstSaberCrystal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecondSaberCrystal {
            get {
                return ((string)(this["SecondSaberCrystal"]));
            }
            set {
                this["SecondSaberCrystal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdSaberCrystal {
            get {
                return ((string)(this["ThirdSaberCrystal"]));
            }
            set {
                this["ThirdSaberCrystal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FourthSaberCrystal {
            get {
                return ((string)(this["FourthSaberCrystal"]));
            }
            set {
                this["FourthSaberCrystal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FifthSaberCrystal {
            get {
                return ((string)(this["FifthSaberCrystal"]));
            }
            set {
                this["FifthSaberCrystal"] = value;
            }
        }
    }
}
