//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWGSetupHolder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstWeaponName {
            get {
                return ((string)(this["FirstWeaponName"]));
            }
            set {
                this["FirstWeaponName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstWeaponDPS {
            get {
                return ((string)(this["FirstWeaponDPS"]));
            }
            set {
                this["FirstWeaponDPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstWeaponElement {
            get {
                return ((string)(this["FirstWeaponElement"]));
            }
            set {
                this["FirstWeaponElement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstWeaponExotics {
            get {
                return ((string)(this["FirstWeaponExotics"]));
            }
            set {
                this["FirstWeaponExotics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecondSetupName {
            get {
                return ((string)(this["SecondSetupName"]));
            }
            set {
                this["SecondSetupName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdSetupName {
            get {
                return ((string)(this["ThirdSetupName"]));
            }
            set {
                this["ThirdSetupName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FourthSetupName {
            get {
                return ((string)(this["FourthSetupName"]));
            }
            set {
                this["FourthSetupName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FifthSetupName {
            get {
                return ((string)(this["FifthSetupName"]));
            }
            set {
                this["FifthSetupName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentSetupNumber {
            get {
                return ((string)(this["CurrentSetupNumber"]));
            }
            set {
                this["CurrentSetupNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstSetupProfession {
            get {
                return ((string)(this["FirstSetupProfession"]));
            }
            set {
                this["FirstSetupProfession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecondSetupProfession {
            get {
                return ((string)(this["SecondSetupProfession"]));
            }
            set {
                this["SecondSetupProfession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdSetupProfession {
            get {
                return ((string)(this["ThirdSetupProfession"]));
            }
            set {
                this["ThirdSetupProfession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FourthSetupProfession {
            get {
                return ((string)(this["FourthSetupProfession"]));
            }
            set {
                this["FourthSetupProfession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FifthSetupProfession {
            get {
                return ((string)(this["FifthSetupProfession"]));
            }
            set {
                this["FifthSetupProfession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstSetupExpertise {
            get {
                return ((string)(this["FirstSetupExpertise"]));
            }
            set {
                this["FirstSetupExpertise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecondSetupExpertise {
            get {
                return ((string)(this["SecondSetupExpertise"]));
            }
            set {
                this["SecondSetupExpertise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdSetupExpertise {
            get {
                return ((string)(this["ThirdSetupExpertise"]));
            }
            set {
                this["ThirdSetupExpertise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FourthSetupExpertise {
            get {
                return ((string)(this["FourthSetupExpertise"]));
            }
            set {
                this["FourthSetupExpertise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FifthSetupExpertise {
            get {
                return ((string)(this["FifthSetupExpertise"]));
            }
            set {
                this["FifthSetupExpertise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstSetupName {
            get {
                return ((string)(this["FirstSetupName"]));
            }
            set {
                this["FirstSetupName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GetCurrentSetupNumber {
            get {
                return ((string)(this["GetCurrentSetupNumber"]));
            }
            set {
                this["GetCurrentSetupNumber"] = value;
            }
        }
    }
}
